//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXWebApplication1.DataModel.KUTA_ECA
{

    public partial class bias : main
    {
        picket fpicket_beg_id;
        [Indexed(Name = @"ipicket_beg_id_bias")]
        [Size(10)]
        [Association(@"biasReferencespicket")]
        [DevExpress.Xpo.DisplayName(@"ПК")]
        public picket picket_beg_id
        {
            get { return fpicket_beg_id; }
            set { SetPropertyValue<picket>("picket_beg_id", ref fpicket_beg_id, value); }
        }
        decimal foffset_beg;
        [DevExpress.Xpo.DisplayName(@"Плюсовка")]
        public decimal offset_beg
        {
            get { return foffset_beg; }
            set { SetPropertyValue<decimal>("offset_beg", ref foffset_beg, value); }
        }
        picket fpicket_end_id;
        [Indexed(Name = @"ipicket_end_id_bias")]
        [Size(10)]
        [Association(@"biasReferencespicket1")]
        [DevExpress.Xpo.DisplayName(@"ПК")]
        public picket picket_end_id
        {
            get { return fpicket_end_id; }
            set { SetPropertyValue<picket>("picket_end_id", ref fpicket_end_id, value); }
        }
        decimal foffset_end;
        [DevExpress.Xpo.DisplayName(@"Плюсовка")]
        public decimal offset_end
        {
            get { return foffset_end; }
            set { SetPropertyValue<decimal>("offset_end", ref foffset_end, value); }
        }
        decimal fbias_value;
        [DevExpress.Xpo.DisplayName(@"Уклон, м")]
        public decimal bias_value
        {
            get { return fbias_value; }
            set { SetPropertyValue<decimal>("bias_value", ref fbias_value, value); }
        }
        decimal fdistance;
        [DevExpress.Xpo.DisplayName(@"Расстояние, м")]
        public decimal distance
        {
            get { return fdistance; }
            set { SetPropertyValue<decimal>("distance", ref fdistance, value); }
        }
        string fprofil_type;
        [Size(75)]
        public string profil_type
        {
            get { return fprofil_type; }
            set { SetPropertyValue<string>("profil_type", ref fprofil_type, value); }
        }
        sheets fsheet_id;
        [Indexed(Name = @"isheet_id_bias")]
        [Size(38)]
        [Association(@"biasReferencessheets")]
        [DevExpress.Xpo.DisplayName(@"Номер листа")]
        public sheets sheet_id
        {
            get { return fsheet_id; }
            set { SetPropertyValue<sheets>("sheet_id", ref fsheet_id, value); }
        }
        decimal fexpl_km_beg;
        [Indexed(Name = @"bias_expl_beg_idx")]
        public decimal expl_km_beg
        {
            get { return fexpl_km_beg; }
            set { SetPropertyValue<decimal>("expl_km_beg", ref fexpl_km_beg, value); }
        }
        decimal fexpl_km_end;
        [Indexed(Name = @"bias_expl_end_idx")]
        public decimal expl_km_end
        {
            get { return fexpl_km_end; }
            set { SetPropertyValue<decimal>("expl_km_end", ref fexpl_km_end, value); }
        }
        decimal frow_index;
        public decimal row_index
        {
            get { return frow_index; }
            set { SetPropertyValue<decimal>("row_index", ref frow_index, value); }
        }
        [PersistentAlias("[sheet_id].[file_name]")]
        public string file_name
        {
            get { return (string)(EvaluateAlias("file_name")); }
        }
    }

}
