//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXWebApplication1.DataModel.KUTA_ECA
{

    public partial class geoprocess : main
    {
        string fegp_number;
        [Indexed(Name = @"geoprocess_number_idx")]
        [Size(6)]
        public string egp_number
        {
            get { return fegp_number; }
            set { SetPropertyValue<string>("egp_number", ref fegp_number, value); }
        }
        string fegp_process;
        [Size(150)]
        public string egp_process
        {
            get { return fegp_process; }
            set { SetPropertyValue<string>("egp_process", ref fegp_process, value); }
        }
        string fdiv_id;
        [Size(75)]
        public string div_id
        {
            get { return fdiv_id; }
            set { SetPropertyValue<string>("div_id", ref fdiv_id, value); }
        }
        decimal fegp_beg_km;
        public decimal egp_beg_km
        {
            get { return fegp_beg_km; }
            set { SetPropertyValue<decimal>("egp_beg_km", ref fegp_beg_km, value); }
        }
        string fegp_beg_section;
        [Size(6)]
        public string egp_beg_section
        {
            get { return fegp_beg_section; }
            set { SetPropertyValue<string>("egp_beg_section", ref fegp_beg_section, value); }
        }
        decimal fegp_end_km;
        public decimal egp_end_km
        {
            get { return fegp_end_km; }
            set { SetPropertyValue<decimal>("egp_end_km", ref fegp_end_km, value); }
        }
        string fegp_end_section;
        [Size(6)]
        public string egp_end_section
        {
            get { return fegp_end_section; }
            set { SetPropertyValue<string>("egp_end_section", ref fegp_end_section, value); }
        }
        string fgab_length;
        [Size(SizeAttribute.Unlimited)]
        public string gab_length
        {
            get { return fgab_length; }
            set { SetPropertyValue<string>("gab_length", ref fgab_length, value); }
        }
        string fgab_width;
        [Size(SizeAttribute.Unlimited)]
        public string gab_width
        {
            get { return fgab_width; }
            set { SetPropertyValue<string>("gab_width", ref fgab_width, value); }
        }
        string fgab_power;
        [Size(SizeAttribute.Unlimited)]
        public string gab_power
        {
            get { return fgab_power; }
            set { SetPropertyValue<string>("gab_power", ref fgab_power, value); }
        }
        string fgab_depth;
        [Size(SizeAttribute.Unlimited)]
        public string gab_depth
        {
            get { return fgab_depth; }
            set { SetPropertyValue<string>("gab_depth", ref fgab_depth, value); }
        }
        string fgab_distance;
        [Size(SizeAttribute.Unlimited)]
        public string gab_distance
        {
            get { return fgab_distance; }
            set { SetPropertyValue<string>("gab_distance", ref fgab_distance, value); }
        }
        string fres_type;
        [Size(150)]
        public string res_type
        {
            get { return fres_type; }
            set { SetPropertyValue<string>("res_type", ref fres_type, value); }
        }
        DateTime fres_date;
        public DateTime res_date
        {
            get { return fres_date; }
            set { SetPropertyValue<DateTime>("res_date", ref fres_date, value); }
        }
        string fres_report;
        [Size(150)]
        public string res_report
        {
            get { return fres_report; }
            set { SetPropertyValue<string>("res_report", ref fres_report, value); }
        }
        string fres_presence;
        [Size(150)]
        public string res_presence
        {
            get { return fres_presence; }
            set { SetPropertyValue<string>("res_presence", ref fres_presence, value); }
        }
        decimal freestr_number;
        public decimal reestr_number
        {
            get { return freestr_number; }
            set { SetPropertyValue<decimal>("reestr_number", ref freestr_number, value); }
        }
        decimal freport_year;
        public decimal report_year
        {
            get { return freport_year; }
            set { SetPropertyValue<decimal>("report_year", ref freport_year, value); }
        }
        decimal fbeg_x;
        public decimal beg_x
        {
            get { return fbeg_x; }
            set { SetPropertyValue<decimal>("beg_x", ref fbeg_x, value); }
        }
        decimal fbeg_y;
        public decimal beg_y
        {
            get { return fbeg_y; }
            set { SetPropertyValue<decimal>("beg_y", ref fbeg_y, value); }
        }
        decimal fend_x;
        public decimal end_x
        {
            get { return fend_x; }
            set { SetPropertyValue<decimal>("end_x", ref fend_x, value); }
        }
        decimal fend_y;
        public decimal end_y
        {
            get { return fend_y; }
            set { SetPropertyValue<decimal>("end_y", ref fend_y, value); }
        }
        string fsect_nums;
        public string sect_nums
        {
            get { return fsect_nums; }
            set { SetPropertyValue<string>("sect_nums", ref fsect_nums, value); }
        }
    }

}
