//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXWebApplication1.DataModel.KUTA_ECA
{

    public partial class high_point : main
    {
        picket fpicket_id;
        [Indexed(Name = @"ipicket_id_high_point")]
        [Size(10)]
        [Association(@"high_pointReferencespicket")]
        public picket picket_id
        {
            get { return fpicket_id; }
            set { SetPropertyValue<picket>("picket_id", ref fpicket_id, value); }
        }
        decimal fofst;
        public decimal ofst
        {
            get { return fofst; }
            set { SetPropertyValue<decimal>("ofst", ref fofst, value); }
        }
        decimal ftrunch_depth;
        public decimal trunch_depth
        {
            get { return ftrunch_depth; }
            set { SetPropertyValue<decimal>("trunch_depth", ref ftrunch_depth, value); }
        }
        decimal fbottom_pipe_point;
        public decimal bottom_pipe_point
        {
            get { return fbottom_pipe_point; }
            set { SetPropertyValue<decimal>("bottom_pipe_point", ref fbottom_pipe_point, value); }
        }
        decimal fground_point;
        public decimal ground_point
        {
            get { return fground_point; }
            set { SetPropertyValue<decimal>("ground_point", ref fground_point, value); }
        }
        decimal fpoint_distance;
        public decimal point_distance
        {
            get { return fpoint_distance; }
            set { SetPropertyValue<decimal>("point_distance", ref fpoint_distance, value); }
        }
        sheets fsheet_id;
        [Size(38)]
        [Association(@"high_pointReferencessheets")]
        public sheets sheet_id
        {
            get { return fsheet_id; }
            set { SetPropertyValue<sheets>("sheet_id", ref fsheet_id, value); }
        }
        decimal fexpl_km;
        [Indexed(Name = @"hpexpl_km_idx")]
        public decimal expl_km
        {
            get { return fexpl_km; }
            set { SetPropertyValue<decimal>("expl_km", ref fexpl_km, value); }
        }
        decimal frow_index;
        public decimal row_index
        {
            get { return frow_index; }
            set { SetPropertyValue<decimal>("row_index", ref frow_index, value); }
        }
        decimal fsum_distance;
        public decimal sum_distance
        {
            get { return fsum_distance; }
            set { SetPropertyValue<decimal>("sum_distance", ref fsum_distance, value); }
        }
        decimal fdiametr;
        public decimal diametr
        {
            get { return fdiametr; }
            set { SetPropertyValue<decimal>("diametr", ref fdiametr, value); }
        }
        decimal faverage_wt;
        public decimal average_wt
        {
            get { return faverage_wt; }
            set { SetPropertyValue<decimal>("average_wt", ref faverage_wt, value); }
        }
        decimal faxis_height;
        public decimal axis_height
        {
            get { return faxis_height; }
            set { SetPropertyValue<decimal>("axis_height", ref faxis_height, value); }
        }
        decimal faxis_depth;
        public decimal axis_depth
        {
            get { return faxis_depth; }
            set { SetPropertyValue<decimal>("axis_depth", ref faxis_depth, value); }
        }
        [PersistentAlias("[sheet_id].[file_name]")]
        public string file_name
        {
            get { return (string)(EvaluateAlias("file_name")); }
        }
    }

}
