//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXWebApplication1.DataModel.KUTA_ECA
{

    public partial class ige : XPLiteObject
    {
        string fige_id;
        [Key]
        [Size(38)]
        public string ige_id
        {
            get { return fige_id; }
            set { SetPropertyValue<string>("ige_id", ref fige_id, value); }
        }
        string fc_2;
        [Size(SizeAttribute.Unlimited)]
        public string c_2
        {
            get { return fc_2; }
            set { SetPropertyValue<string>("c_2", ref fc_2, value); }
        }
        string fc_3;
        [Size(SizeAttribute.Unlimited)]
        public string c_3
        {
            get { return fc_3; }
            set { SetPropertyValue<string>("c_3", ref fc_3, value); }
        }
        string fc_4;
        [Size(SizeAttribute.Unlimited)]
        public string c_4
        {
            get { return fc_4; }
            set { SetPropertyValue<string>("c_4", ref fc_4, value); }
        }
        string fc_5;
        [Size(SizeAttribute.Unlimited)]
        public string c_5
        {
            get { return fc_5; }
            set { SetPropertyValue<string>("c_5", ref fc_5, value); }
        }
        string fc_6;
        [Size(SizeAttribute.Unlimited)]
        public string c_6
        {
            get { return fc_6; }
            set { SetPropertyValue<string>("c_6", ref fc_6, value); }
        }
        string fc_7;
        [Size(SizeAttribute.Unlimited)]
        public string c_7
        {
            get { return fc_7; }
            set { SetPropertyValue<string>("c_7", ref fc_7, value); }
        }
        string fc_8;
        [Size(SizeAttribute.Unlimited)]
        public string c_8
        {
            get { return fc_8; }
            set { SetPropertyValue<string>("c_8", ref fc_8, value); }
        }
        string fc_9;
        [Size(SizeAttribute.Unlimited)]
        public string c_9
        {
            get { return fc_9; }
            set { SetPropertyValue<string>("c_9", ref fc_9, value); }
        }
        string fc_10;
        [Size(SizeAttribute.Unlimited)]
        public string c_10
        {
            get { return fc_10; }
            set { SetPropertyValue<string>("c_10", ref fc_10, value); }
        }
        string fc_11;
        [Size(SizeAttribute.Unlimited)]
        public string c_11
        {
            get { return fc_11; }
            set { SetPropertyValue<string>("c_11", ref fc_11, value); }
        }
        string fc_12;
        [Size(SizeAttribute.Unlimited)]
        public string c_12
        {
            get { return fc_12; }
            set { SetPropertyValue<string>("c_12", ref fc_12, value); }
        }
        string fc_13;
        [Size(SizeAttribute.Unlimited)]
        public string c_13
        {
            get { return fc_13; }
            set { SetPropertyValue<string>("c_13", ref fc_13, value); }
        }
        string fc_14;
        [Size(SizeAttribute.Unlimited)]
        public string c_14
        {
            get { return fc_14; }
            set { SetPropertyValue<string>("c_14", ref fc_14, value); }
        }
        string fc_15;
        [Size(SizeAttribute.Unlimited)]
        public string c_15
        {
            get { return fc_15; }
            set { SetPropertyValue<string>("c_15", ref fc_15, value); }
        }
        string fc_16;
        [Size(SizeAttribute.Unlimited)]
        public string c_16
        {
            get { return fc_16; }
            set { SetPropertyValue<string>("c_16", ref fc_16, value); }
        }
        string fc_17;
        [Size(SizeAttribute.Unlimited)]
        public string c_17
        {
            get { return fc_17; }
            set { SetPropertyValue<string>("c_17", ref fc_17, value); }
        }
        string fc_18;
        [Size(SizeAttribute.Unlimited)]
        public string c_18
        {
            get { return fc_18; }
            set { SetPropertyValue<string>("c_18", ref fc_18, value); }
        }
        string fc_19;
        [Size(SizeAttribute.Unlimited)]
        public string c_19
        {
            get { return fc_19; }
            set { SetPropertyValue<string>("c_19", ref fc_19, value); }
        }
        string fc_20;
        [Size(SizeAttribute.Unlimited)]
        public string c_20
        {
            get { return fc_20; }
            set { SetPropertyValue<string>("c_20", ref fc_20, value); }
        }
        string fc_21;
        [Size(SizeAttribute.Unlimited)]
        public string c_21
        {
            get { return fc_21; }
            set { SetPropertyValue<string>("c_21", ref fc_21, value); }
        }
        string fc_22;
        [Size(SizeAttribute.Unlimited)]
        public string c_22
        {
            get { return fc_22; }
            set { SetPropertyValue<string>("c_22", ref fc_22, value); }
        }
        string fc_23;
        [Size(SizeAttribute.Unlimited)]
        public string c_23
        {
            get { return fc_23; }
            set { SetPropertyValue<string>("c_23", ref fc_23, value); }
        }
        string fc_24;
        [Size(SizeAttribute.Unlimited)]
        public string c_24
        {
            get { return fc_24; }
            set { SetPropertyValue<string>("c_24", ref fc_24, value); }
        }
        string fc_25;
        [Size(SizeAttribute.Unlimited)]
        public string c_25
        {
            get { return fc_25; }
            set { SetPropertyValue<string>("c_25", ref fc_25, value); }
        }
        string fc_26;
        [Size(SizeAttribute.Unlimited)]
        public string c_26
        {
            get { return fc_26; }
            set { SetPropertyValue<string>("c_26", ref fc_26, value); }
        }
        string fc_27;
        [Size(SizeAttribute.Unlimited)]
        public string c_27
        {
            get { return fc_27; }
            set { SetPropertyValue<string>("c_27", ref fc_27, value); }
        }
        string fc_28;
        [Size(SizeAttribute.Unlimited)]
        public string c_28
        {
            get { return fc_28; }
            set { SetPropertyValue<string>("c_28", ref fc_28, value); }
        }
        string fc_29;
        [Size(SizeAttribute.Unlimited)]
        public string c_29
        {
            get { return fc_29; }
            set { SetPropertyValue<string>("c_29", ref fc_29, value); }
        }
        string fc_30;
        [Size(SizeAttribute.Unlimited)]
        public string c_30
        {
            get { return fc_30; }
            set { SetPropertyValue<string>("c_30", ref fc_30, value); }
        }
        string fc_31;
        [Size(SizeAttribute.Unlimited)]
        public string c_31
        {
            get { return fc_31; }
            set { SetPropertyValue<string>("c_31", ref fc_31, value); }
        }
        string fc_32;
        [Size(SizeAttribute.Unlimited)]
        public string c_32
        {
            get { return fc_32; }
            set { SetPropertyValue<string>("c_32", ref fc_32, value); }
        }
        string fc_33;
        [Size(SizeAttribute.Unlimited)]
        public string c_33
        {
            get { return fc_33; }
            set { SetPropertyValue<string>("c_33", ref fc_33, value); }
        }
        string fc_34;
        [Size(SizeAttribute.Unlimited)]
        public string c_34
        {
            get { return fc_34; }
            set { SetPropertyValue<string>("c_34", ref fc_34, value); }
        }
        string fc_35;
        [Size(SizeAttribute.Unlimited)]
        public string c_35
        {
            get { return fc_35; }
            set { SetPropertyValue<string>("c_35", ref fc_35, value); }
        }
        string fc_36;
        [Size(SizeAttribute.Unlimited)]
        public string c_36
        {
            get { return fc_36; }
            set { SetPropertyValue<string>("c_36", ref fc_36, value); }
        }
        string fc_37;
        [Size(SizeAttribute.Unlimited)]
        public string c_37
        {
            get { return fc_37; }
            set { SetPropertyValue<string>("c_37", ref fc_37, value); }
        }
        string fc_38;
        [Size(SizeAttribute.Unlimited)]
        public string c_38
        {
            get { return fc_38; }
            set { SetPropertyValue<string>("c_38", ref fc_38, value); }
        }
        string fc_39;
        [Size(SizeAttribute.Unlimited)]
        public string c_39
        {
            get { return fc_39; }
            set { SetPropertyValue<string>("c_39", ref fc_39, value); }
        }
        string fc_40;
        [Size(SizeAttribute.Unlimited)]
        public string c_40
        {
            get { return fc_40; }
            set { SetPropertyValue<string>("c_40", ref fc_40, value); }
        }
        string fc_41;
        [Size(SizeAttribute.Unlimited)]
        public string c_41
        {
            get { return fc_41; }
            set { SetPropertyValue<string>("c_41", ref fc_41, value); }
        }
        string fc_42;
        [Size(SizeAttribute.Unlimited)]
        public string c_42
        {
            get { return fc_42; }
            set { SetPropertyValue<string>("c_42", ref fc_42, value); }
        }
        string fc_43;
        [Size(SizeAttribute.Unlimited)]
        public string c_43
        {
            get { return fc_43; }
            set { SetPropertyValue<string>("c_43", ref fc_43, value); }
        }
        string fc_44;
        [Size(SizeAttribute.Unlimited)]
        public string c_44
        {
            get { return fc_44; }
            set { SetPropertyValue<string>("c_44", ref fc_44, value); }
        }
        string fc_45;
        [Size(SizeAttribute.Unlimited)]
        public string c_45
        {
            get { return fc_45; }
            set { SetPropertyValue<string>("c_45", ref fc_45, value); }
        }
        string fc_46;
        [Size(SizeAttribute.Unlimited)]
        public string c_46
        {
            get { return fc_46; }
            set { SetPropertyValue<string>("c_46", ref fc_46, value); }
        }
        string fc_47;
        [Size(SizeAttribute.Unlimited)]
        public string c_47
        {
            get { return fc_47; }
            set { SetPropertyValue<string>("c_47", ref fc_47, value); }
        }
        string fc_48;
        [Size(SizeAttribute.Unlimited)]
        public string c_48
        {
            get { return fc_48; }
            set { SetPropertyValue<string>("c_48", ref fc_48, value); }
        }
        string fc_49;
        [Size(SizeAttribute.Unlimited)]
        public string c_49
        {
            get { return fc_49; }
            set { SetPropertyValue<string>("c_49", ref fc_49, value); }
        }
        string fc_50;
        [Size(SizeAttribute.Unlimited)]
        public string c_50
        {
            get { return fc_50; }
            set { SetPropertyValue<string>("c_50", ref fc_50, value); }
        }
        string fc_51;
        [Size(SizeAttribute.Unlimited)]
        public string c_51
        {
            get { return fc_51; }
            set { SetPropertyValue<string>("c_51", ref fc_51, value); }
        }
        string fc_52;
        [Size(SizeAttribute.Unlimited)]
        public string c_52
        {
            get { return fc_52; }
            set { SetPropertyValue<string>("c_52", ref fc_52, value); }
        }
        string fc_53;
        [Size(SizeAttribute.Unlimited)]
        public string c_53
        {
            get { return fc_53; }
            set { SetPropertyValue<string>("c_53", ref fc_53, value); }
        }
        string fc_54;
        [Size(SizeAttribute.Unlimited)]
        public string c_54
        {
            get { return fc_54; }
            set { SetPropertyValue<string>("c_54", ref fc_54, value); }
        }
        string fc_55;
        [Size(SizeAttribute.Unlimited)]
        public string c_55
        {
            get { return fc_55; }
            set { SetPropertyValue<string>("c_55", ref fc_55, value); }
        }
        string fc_56;
        [Size(SizeAttribute.Unlimited)]
        public string c_56
        {
            get { return fc_56; }
            set { SetPropertyValue<string>("c_56", ref fc_56, value); }
        }
        string fc_57;
        [Size(SizeAttribute.Unlimited)]
        public string c_57
        {
            get { return fc_57; }
            set { SetPropertyValue<string>("c_57", ref fc_57, value); }
        }
        string fc_58;
        [Size(SizeAttribute.Unlimited)]
        public string c_58
        {
            get { return fc_58; }
            set { SetPropertyValue<string>("c_58", ref fc_58, value); }
        }
        string fc_59;
        [Size(SizeAttribute.Unlimited)]
        public string c_59
        {
            get { return fc_59; }
            set { SetPropertyValue<string>("c_59", ref fc_59, value); }
        }
        string fc_60;
        [Size(SizeAttribute.Unlimited)]
        public string c_60
        {
            get { return fc_60; }
            set { SetPropertyValue<string>("c_60", ref fc_60, value); }
        }
        string fc_61;
        [Size(SizeAttribute.Unlimited)]
        public string c_61
        {
            get { return fc_61; }
            set { SetPropertyValue<string>("c_61", ref fc_61, value); }
        }
        string fc_62;
        [Size(SizeAttribute.Unlimited)]
        public string c_62
        {
            get { return fc_62; }
            set { SetPropertyValue<string>("c_62", ref fc_62, value); }
        }
        string fc_63;
        [Size(SizeAttribute.Unlimited)]
        public string c_63
        {
            get { return fc_63; }
            set { SetPropertyValue<string>("c_63", ref fc_63, value); }
        }
        string fc_64;
        [Size(SizeAttribute.Unlimited)]
        public string c_64
        {
            get { return fc_64; }
            set { SetPropertyValue<string>("c_64", ref fc_64, value); }
        }
        string fc_65;
        [Size(SizeAttribute.Unlimited)]
        public string c_65
        {
            get { return fc_65; }
            set { SetPropertyValue<string>("c_65", ref fc_65, value); }
        }
        string fc_66;
        [Size(SizeAttribute.Unlimited)]
        public string c_66
        {
            get { return fc_66; }
            set { SetPropertyValue<string>("c_66", ref fc_66, value); }
        }
        string fc_67;
        [Size(SizeAttribute.Unlimited)]
        public string c_67
        {
            get { return fc_67; }
            set { SetPropertyValue<string>("c_67", ref fc_67, value); }
        }
        string fc_68;
        [Size(SizeAttribute.Unlimited)]
        public string c_68
        {
            get { return fc_68; }
            set { SetPropertyValue<string>("c_68", ref fc_68, value); }
        }
        string fc_69;
        [Size(SizeAttribute.Unlimited)]
        public string c_69
        {
            get { return fc_69; }
            set { SetPropertyValue<string>("c_69", ref fc_69, value); }
        }
        string fc_70;
        [Size(SizeAttribute.Unlimited)]
        public string c_70
        {
            get { return fc_70; }
            set { SetPropertyValue<string>("c_70", ref fc_70, value); }
        }
        string fc_71;
        [Size(SizeAttribute.Unlimited)]
        public string c_71
        {
            get { return fc_71; }
            set { SetPropertyValue<string>("c_71", ref fc_71, value); }
        }
        string fc_72;
        [Size(SizeAttribute.Unlimited)]
        public string c_72
        {
            get { return fc_72; }
            set { SetPropertyValue<string>("c_72", ref fc_72, value); }
        }
        string fc_73;
        [Size(SizeAttribute.Unlimited)]
        public string c_73
        {
            get { return fc_73; }
            set { SetPropertyValue<string>("c_73", ref fc_73, value); }
        }
        string fc_74;
        [Size(SizeAttribute.Unlimited)]
        public string c_74
        {
            get { return fc_74; }
            set { SetPropertyValue<string>("c_74", ref fc_74, value); }
        }
        string fc_75;
        [Size(SizeAttribute.Unlimited)]
        public string c_75
        {
            get { return fc_75; }
            set { SetPropertyValue<string>("c_75", ref fc_75, value); }
        }
        string fc_76;
        [Size(SizeAttribute.Unlimited)]
        public string c_76
        {
            get { return fc_76; }
            set { SetPropertyValue<string>("c_76", ref fc_76, value); }
        }
        string fc_77;
        [Size(SizeAttribute.Unlimited)]
        public string c_77
        {
            get { return fc_77; }
            set { SetPropertyValue<string>("c_77", ref fc_77, value); }
        }
        string fc_78;
        [Size(SizeAttribute.Unlimited)]
        public string c_78
        {
            get { return fc_78; }
            set { SetPropertyValue<string>("c_78", ref fc_78, value); }
        }
        string fc_79;
        [Size(SizeAttribute.Unlimited)]
        public string c_79
        {
            get { return fc_79; }
            set { SetPropertyValue<string>("c_79", ref fc_79, value); }
        }
        string fc_80;
        [Size(SizeAttribute.Unlimited)]
        public string c_80
        {
            get { return fc_80; }
            set { SetPropertyValue<string>("c_80", ref fc_80, value); }
        }
    }

}
