//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXWebApplication1.DataModel.KUTA_ECA
{

    public partial class main : XPBaseObject
    {
        char fis_active;
        public char is_active
        {
            get { return fis_active; }
            set { SetPropertyValue<char>("is_active", ref fis_active, value); }
        }
        string fmain_type;
        [Size(38)]
        public string main_type
        {
            get { return fmain_type; }
            set { SetPropertyValue<string>("main_type", ref fmain_type, value); }
        }
        decimal fdiv_code;
        public decimal div_code
        {
            get { return fdiv_code; }
            set { SetPropertyValue<decimal>("div_code", ref fdiv_code, value); }
        }
        string fmain_id;
        [Key]
        [Size(38)]
        public string main_id
        {
            get { return fmain_id; }
            set { SetPropertyValue<string>("main_id", ref fmain_id, value); }
        }
    }

}
