//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXWebApplication1.DataModel.KUTA_ECA
{

    public partial class picket : XPLiteObject
    {
        string fpicket_id;
        [Key]
        public string picket_id
        {
            get { return fpicket_id; }
            set { SetPropertyValue<string>("picket_id", ref fpicket_id, value); }
        }
        decimal fpicket_value;
        public decimal picket_value
        {
            get { return fpicket_value; }
            set { SetPropertyValue<decimal>("picket_value", ref fpicket_value, value); }
        }
        decimal fpicket_point;
        public decimal picket_point
        {
            get { return fpicket_point; }
            set { SetPropertyValue<decimal>("picket_point", ref fpicket_point, value); }
        }
        string fpicket_point_view;
        public string picket_point_view
        {
            get { return fpicket_point_view; }
            set { SetPropertyValue<string>("picket_point_view", ref fpicket_point_view, value); }
        }
        string fpicket_value_view;
        public string picket_value_view
        {
            get { return fpicket_value_view; }
            set { SetPropertyValue<string>("picket_value_view", ref fpicket_value_view, value); }
        }
        string flength;
        public string length
        {
            get { return flength; }
            set { SetPropertyValue<string>("length", ref flength, value); }
        }
        string fdistance;
        public string distance
        {
            get { return fdistance; }
            set { SetPropertyValue<string>("distance", ref fdistance, value); }
        }
        string fexpl_km;
        public string expl_km
        {
            get { return fexpl_km; }
            set { SetPropertyValue<string>("expl_km", ref fexpl_km, value); }
        }
        [Association(@"biasReferencespicket")]
        public XPCollection<bias> biasCollection { get { return GetCollection<bias>("biasCollection"); } }
        [Association(@"biasReferencespicket1")]
        public XPCollection<bias> biasCollection1 { get { return GetCollection<bias>("biasCollection1"); } }
        [Association(@"turning_anglesReferencespicket")]
        public XPCollection<turning_angles> turning_angless { get { return GetCollection<turning_angles>("turning_angless"); } }
        [Association(@"uzaReferencespicket")]
        public XPCollection<uza> uzas { get { return GetCollection<uza>("uzas"); } }
        [Association(@"valvesReferencespicket")]
        public XPCollection<valves> valvesCollection { get { return GetCollection<valves>("valvesCollection"); } }
        [Association(@"high_pointReferencespicket")]
        public XPCollection<high_point> high_points { get { return GetCollection<high_point>("high_points"); } }
        [Association(@"sheetsReferencespicket")]
        public XPCollection<sheets> sheetsCollection { get { return GetCollection<sheets>("sheetsCollection"); } }
        [Association(@"sheetsReferencespicket1")]
        public XPCollection<sheets> sheetsCollection1 { get { return GetCollection<sheets>("sheetsCollection1"); } }
    }

}
