//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXWebApplication1.DataModel.KUTA_ECA
{

    public partial class uza : main
    {
        decimal fground_point;
        public decimal ground_point
        {
            get { return fground_point; }
            set { SetPropertyValue<decimal>("ground_point", ref fground_point, value); }
        }
        decimal fpipe_bottom_point;
        public decimal pipe_bottom_point
        {
            get { return fpipe_bottom_point; }
            set { SetPropertyValue<decimal>("pipe_bottom_point", ref fpipe_bottom_point, value); }
        }
        decimal ftrench_depth;
        public decimal trench_depth
        {
            get { return ftrench_depth; }
            set { SetPropertyValue<decimal>("trench_depth", ref ftrench_depth, value); }
        }
        picket fpicket_id;
        [Indexed(Name = @"ipicket_id_uza")]
        [Size(10)]
        [Association(@"uzaReferencespicket")]
        public picket picket_id
        {
            get { return fpicket_id; }
            set { SetPropertyValue<picket>("picket_id", ref fpicket_id, value); }
        }
        decimal fofst;
        public decimal ofst
        {
            get { return fofst; }
            set { SetPropertyValue<decimal>("ofst", ref fofst, value); }
        }
        sheets fsheet_id;
        [Indexed(Name = @"isheet_id_uza")]
        [Size(38)]
        [Association(@"uzaReferencessheets")]
        public sheets sheet_id
        {
            get { return fsheet_id; }
            set { SetPropertyValue<sheets>("sheet_id", ref fsheet_id, value); }
        }
        decimal fexpl_km;
        public decimal expl_km
        {
            get { return fexpl_km; }
            set { SetPropertyValue<decimal>("expl_km", ref fexpl_km, value); }
        }
        [PersistentAlias("[sheet_id].[file_name]")]
        public string file_name
        {
            get { return (string)(EvaluateAlias("file_name")); }
        }
    }

}
